name: Retrieve GitHub Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-vars:
    runs-on: windows-2019

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}