name: Retrieve GitHub Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-vars:
    runs-on: windows-2019
    environment:
      name: dev #[Environment Name]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: view the vars context
        shell: bash
        run: echo "$VARS_CONTEXT"

        env:
          VARS_CONTEXT: ${{ toJson(vars) }}

      - name: view the vars context dev
        shell: bash
        run: echo "$VARS_CONTEXT"

        env:
          VARS_CONTEXT: ${{ toJson(vars) }}