name: Retrieve GitHub Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-vars:
    runs-on: windows-2019

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: view the vars context
        shell: bash
        run: echo "$VARS_CONTEXT"

        env:
          VARS_CONTEXT: ${{ toJson(vars) }}

      - name: Set environment variables
        run: |
          echo "MY_DEV=dev" >> $GITHUB_ENV

      - name: view the vars context
        shell: bash
        run: echo "$VARS_CONTEXT"

        env:
          VARS_DEV_CONTEXT: ${{ toJson(env.vars) }}