name: Retrieve GitHub Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  retrieve-vars:
    runs-on: windows-2019

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: view the vars context
        shell: bash
        run: echo "$VARS_CONTEXT"

        env:
          VARS_CONTEXT: ${{ toJson(vars) }}

      - name: view the vars context in dev
        shell: bash
        run: echo "$VARS_DEV"

        env:
          VARS_CONTEXT: ${{ toJson(vars) }}

      - name: Dump vars context
        if: github.ref == 'refs/heads/dev'
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}"

#      - name: Set environment variables
#        run: |
#          echo "MY_DEV=dev" >> $GITHUB_ENV
#          echo "MY_SIT=sit" >> $GITHUB_ENV
#
#      - name: View environment variables
#        run: |
#          echo "MY_DEV: $MY_DEV"
#          echo "MY_SIT: $MY_SIT"
#          echo "PATH: $PATH"
#          echo "RUNNER_OS: $RUNNER_OS"
#        env:
#          MY_VAR: ${{ env.MY_DEV }}
#          MY_SIT: ${{ env.MY_SIT }}
#
#      - name: Print all environment variables
#        run: printenv